filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/debug.log
    fields:
      service: geant_web_backend
    multiline.pattern: '^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}.\d{3}\s+\|'
    multiline.negate: true
    multiline.match: after

processors:
  - drop_fields:
      fields: ["agent", "input", "ecs", "log.offset"]

output.logstash:
  hosts: ["${ELK_IP}:5044"]
