version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BASE_S3_URL=${BASE_S3_URL}
      - IS_DEBUG=True
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 && python manage.py search_index --rebuild -f"
    depends_on:
      - database
      - redis
      - elasticsearch

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  elasticsearch:
    image: elasticsearch:8.16.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  worker:
    build:
      context: .
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./core:/core
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BASE_S3_URL=${BASE_S3_URL}

  flower:
    build:
      context: .
    entrypoint: celery
    command: -A core.celery_app flower
    volumes:
      - ./core:/core
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    ports:
      - "5555:5555"

  filebeat_backend:
    image: elastic/filebeat:7.16.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./core/logs:/logs
    environment:
      - ELASTICSEARCH_HOST=${ELK_IP}:9200
      - LOGSTASH_HOST=${ELK_IP}:5044
      - ELK_IP=${ELK_IP}
    command: [ "filebeat", "-e", "-strict.perms=false" ]
    restart: always

volumes:
  db_data:
  esdata:
