version: '3.8'

x-worker-template: &worker-template
  build:
    context: .
  entrypoint: celery
  command: -A celery_app.app worker --loglevel=info
  volumes:
    - ./core:/core
  depends_on:
    - redis
    - database
  environment:
    - DB_HOST=${DB_HOST}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - SECRET_KEY=${SECRET_KEY}
  env_file:
    - .env

services:
  web-app:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./core:/core
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - IS_DEBUG=False
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8001 core.wsgi:application"
    expose:
      - "8001"
    depends_on:
      - database
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerFile
    ports:
      - "81:81"
      - "444:444"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web-app

  database:
    image: postgres:14.6-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker1:
    <<: *worker-template
    hostname: worker1

  worker2:
    <<: *worker-template
    hostname: worker2

  worker3:
    <<: *worker-template
    hostname: worker3

  worker4:
    <<: *worker-template
    hostname: worker4

  celery_beat:
    build:
      context: .
    entrypoint: celery
    volumes:
      - ./core:/core
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
    command: -A core.celery_app beat --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - database

  flower:
    build:
      context: .
    entrypoint: celery
    command: -A core.celery_app flower --port=5555
    volumes:
      - ./core:/core
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "5555:5555"

  filebeat:
    image: elastic/filebeat:7.16.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./core/logs:/logs
    environment:
      - ELASTICSEARCH_HOST=${ELK_IP}:9200
      - LOGSTASH_HOST=${ELK_IP}:5044
      - ELK_IP=${ELK_IP}
    command: [ "filebeat", "-e", "-strict.perms=false" ]
    restart: always

volumes:
  db_data:
