version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=${DB_HOST:-database}
      - DB_NAME=${DB_NAME:-debug_dbname}
      - DB_USER=${DB_USER:-debug_dbuser}
      - DB_PASS=${DB_PASS:-debug_dbpassword}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-debug_redis_password}
      - PATH_TO_LOCAL_STORAGE=${PATH_TO_LOCAL_STORAGE:-files/}
      - STORAGE_URL=${STORAGE_URL:-http://92.63.76.158}
      - WEB_BACKEND_URL=${WEB_BACKEND_URL:-https://92.63.76.159:444}
      - BACKEND_URL=${BACKEND_URL:-http://92.63.76.157}
      - FRONTEND_URL=${FRONTEND_URL:-https://92.63.76.159}
      - REGISTRATION_CONFIRM_SALT=${REGISTRATION_CONFIRM_SALT:-test_rc_salt}
      - PASSWORD_RECOVERY_SALT=${PASSWORD_RECOVERY_SALT:-test_pr_salt}
      - EMAIL_UPDATE_SALT=${EMAIL_UPDATE_SALT:-test_eu_salt}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - IS_DEBUG=True
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000;
             python manage.py search_index --rebuild -f"
    depends_on:
      - database
      - redis
      - elasticsearch

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-debug_dbname}
      - POSTGRES_USER=${POSTGRES_USER:-debug_dbuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-debug_dbpassword}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-debug_redis_password}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-debug_redis_password}

  elasticsearch:
    image: elasticsearch:8.16.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  worker:
    build:
      context: .
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=${DB_HOST:-database}
      - DB_NAME=${DB_NAME:-debug_dbname}
      - DB_USER=${DB_USER:-debug_dbuser}
      - DB_PASS=${DB_PASS:-debug_dbpassword}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-debug_redis_password}
      - BACKEND_URL=${BACKEND_URL:-http://92.63.76.157}
      - SECRET_KEY=${SECRET_KEY}
      - STORAGE_URL=${STORAGE_URL:-http://92.63.76.158}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - PATH_TO_LOCAL_STORAGE=${PATH_TO_LOCAL_STORAGE:-files/}

  celery_beat:
    build:
      context: .
    entrypoint: celery
    volumes:
      - ./core:/core
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST:-database}
      - DB_NAME=${DB_NAME:-debug_dbname}
      - DB_USER=${DB_USER:-debug_dbuser}
      - DB_PASS=${DB_PASS:-debug_dbpassword}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-debug_redis_password}
      - BACKEND_URL=${BACKEND_URL:-http://92.63.76.157}
      - SECRET_KEY=${SECRET_KEY}
      - STORAGE_URL=${STORAGE_URL:-http://92.63.76.158}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    command: -A core.celery_app beat --loglevel=info
    depends_on:
      - redis
      - database

  flower:
    build:
      context: .
    entrypoint: celery
    command: -A core.celery_app flower
    volumes:
      - ./core:/core
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-debug_redis_password}
      - BACKEND_URL=${BACKEND_URL:-http://92.63.76.157}
      - SECRET_KEY=${SECRET_KEY}
      - STORAGE_URL=${STORAGE_URL:-http://92.63.76.158}
    depends_on:
      - redis
    ports:
      - "5555:5555"

  filebeat_backend:
    image: elastic/filebeat:7.16.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./core/logs:/logs
    environment:
      - ELASTICSEARCH_HOST=${ELK_IP:-127.0.0.1}:9200
      - LOGSTASH_HOST=${ELK_IP:-127.0.0.1}:5044
      - ELK_IP=${ELK_IP:-127.0.0.1}
    command: [ "filebeat", "-e", "-strict.perms=false" ]
    restart: always

volumes:
  db_data:
  esdata:
