# Generated by Django 5.1.4 on 2024-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_tests_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date_to_update',
            field=models.DateField(auto_now=True),
        ),
    ]
