# Generated by Django 5.1.5 on 2025-02-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_tests_storage', '0002_alter_testresult_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultfile',
            name='day_to_delete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='day_to_delete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
