# Generated by Django 5.1.5 on 2025-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_tests_storage', '0003_testresultfile_day_to_delete_version_day_to_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'Only version creator can interact with versions and objects related with them'), (2, 'Only part of employees can interact with versions and objects related with them'), (3, 'Only employees can interact with versions and objects related with them')], default=3)),
            ],
            options={
                'verbose_name': 'File mode',
            },
        ),
    ]
