# Generated by Django 5.1.5 on 2025-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_tests_storage', '0004_filemodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodemodel',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Only staff can interact with versions and objects related with them'), (2, 'Only part of employees can interact with versions and objects related with them'), (3, 'Only employees can interact with versions and objects related with them')], default=3),
        ),
    ]
