# Generated by Django 5.1.4 on 2024-12-12 06:45

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key_s3', models.CharField(help_text='in this field encoded all info about example', max_length=255)),
                ('date_to_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.CreateModel(
            name='UserExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UserExample',
                'verbose_name_plural': 'UsersExamples',
                'ordering': ('user', 'creation_date'),
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_tag_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email filed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_char', message="The '@' symbol is not allowed", regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_char', message="The '@' symbol is not allowed", regex='^[\\w-]+$')]),
        ),
        migrations.AddField(
            model_name='example',
            name='users',
            field=models.ManyToManyField(related_name='examples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexample',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_users', to='users.example'),
        ),
        migrations.AddField(
            model_name='userexample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='user_examples', to=settings.AUTH_USER_MODEL),
        ),
    ]
