# Generated by Django 5.1.4 on 2024-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_example_userexample_remove_user_user_email_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='key_s3',
            field=models.CharField(help_text='in this field encoded all info about example', max_length=255, unique=True),
        ),
    ]
