# Generated by Django 5.1.4 on 2024-12-13 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_example_key_s3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_char', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_char', regex='^[\\w-]+$')]),
        ),
    ]
