# Generated by Django 5.1.4 on 2025-01-09 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_tag_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexample',
            name='example',
        ),
        migrations.RemoveField(
            model_name='userexample',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='UserExample',
        ),
    ]
