# Generated by Django 5.1.5 on 2025-02-08 07:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique=True),
        ),
    ]
