# Generated by Django 5.1.5 on 2025-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='For sending messages into email need to verificate email adress', verbose_name='email verification status'),
        ),
    ]
