# Generated by Django 5.1.5 on 2025-04-21 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('element_order', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('text', 'text'), ('csv', 'graphic'), ('webp', 'image'), ('code', 'code'), ('formula', 'formula'), ('subsubscription', 'subsubscription')], default='text', max_length=15)),
            ],
            options={
                'ordering': ('element_order',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('chosen', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='geant_documentation.category')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='geant_documentation.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('format', models.CharField(choices=[('webp', 'webp'), ('csv', 'csv')], default='webp', max_length=4)),
                ('comment', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='geant_documentation.element')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subscription_order', models.PositiveSmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='geant_documentation.article')),
            ],
            options={
                'ordering': ('subscription_order',),
                'unique_together': {('article', 'subscription_order'), ('article', 'title')},
            },
        ),
        migrations.AddField(
            model_name='element',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='geant_documentation.subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('subscription', 'element_order')},
        ),
    ]
