# Generated by Django 5.1.5 on 2025-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_documentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='comment',
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('csv', 'graphic'), ('webp', 'image'), ('formula', 'formula'), ('subsubscription', 'subsubscription')], default='text', max_length=15),
        ),
    ]
