# Generated by Django 5.1.5 on 2025-06-13 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_documentation', '0002_remove_file_comment_alter_element_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='chosen',
        ),
        migrations.CreateModel(
            name='ArticleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_articles', to='geant_documentation.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(related_name='articles', through='geant_documentation.ArticleUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
