# Generated by Django 5.1.5 on 2025-06-13 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geant_documentation', '0003_remove_article_chosen_articleuser_article_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleuser',
            unique_together={('article', 'user')},
        ),
    ]
