# Generated by Django 5.1.4 on 2025-01-09 05:08

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key_s3', models.CharField(help_text='in this field encoded all info about example', max_length=255, unique=True)),
                ('date_to_update', models.DateField(auto_now=True)),
                ('tags', models.ManyToManyField(related_name='examples', to='geant_examples.tag')),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.CreateModel(
            name='UserExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_users', to='geant_examples.example')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='user_examples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserExample',
                'verbose_name_plural': 'UsersExamples',
                'ordering': ('user', 'creation_date'),
            },
        ),
        migrations.AddField(
            model_name='example',
            name='users',
            field=models.ManyToManyField(related_name='examples', through='geant_examples.UserExample', to=settings.AUTH_USER_MODEL),
        ),
    ]
