# Generated by Django 5.1.5 on 2025-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='category',
            field=models.CharField(choices=[('default', 'Default category')], default='default', help_text='Category of example', max_length=255),
        ),
    ]
