# Generated by Django 5.1.5 on 2025-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0002_example_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexample',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In process'), (1, 'Completed'), (2, 'Examples was never executed')], default=2, help_text='Current status of example executing'),
        ),
    ]
