# Generated by Django 5.1.5 on 2025-02-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0003_userexample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='examples', to='geant_examples.tag'),
        ),
    ]
