# Generated by Django 5.1.5 on 2025-02-21 16:06

import django.db.models.deletion
import geant_examples.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0004_alter_example_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplesTitleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_verbose', models.CharField(max_length=255, unique=True)),
                ('title_not_verbose', models.CharField(max_length=10, unique=True, validators=[geant_examples.validators.title_not_verbose_view])),
            ],
            options={
                'verbose_name': 'Possible meanings of Examples titles',
                'verbose_name_plural': 'Possible meanings of Examples titles',
                'ordering': ('title_not_verbose',),
            },
        ),
        migrations.RemoveField(
            model_name='example',
            name='key_s3',
        ),
        migrations.CreateModel(
            name='ExampleGeant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title format should be like: TSU_XX_00. Title will be selected automatically, after selecting FK', max_length=10)),
                ('key_s3', models.CharField(help_text='in this field encoded all info about example', max_length=255, unique=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_geant', to='geant_examples.example')),
            ],
            options={
                'verbose_name': 'ExampleGeant',
                'verbose_name_plural': 'ExamplesGeant',
            },
        ),
    ]
