# Generated by Django 5.1.5 on 2025-02-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0005_examplestitlerelation_remove_example_key_s3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplegeant',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples_geant', to='geant_examples.example'),
        ),
    ]
