# Generated by Django 5.1.5 on 2025-03-26 19:41

import django.db.models.deletion
import django.db.models.expressions
import geant_examples.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0006_alter_examplegeant_example'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_s3', models.CharField(help_text='in this field encoded all info about example', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ExampleCommand',
                'verbose_name_plural': 'ExampleCommands',
            },
        ),
        migrations.CreateModel(
            name='UserExampleCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'In process'), (1, 'Completed'), (2, 'Executing failure')], default=0, help_text='Current status of example executing')),
            ],
            options={
                'verbose_name': 'UserExampleCommand',
                'verbose_name_plural': 'UsersExampleCommands',
                'ordering': ('user', 'creation_date'),
            },
        ),
        migrations.RemoveField(
            model_name='examplegeant',
            name='example',
        ),
        migrations.DeleteModel(
            name='ExamplesTitleRelation',
        ),
        migrations.RemoveField(
            model_name='userexample',
            name='example',
        ),
        migrations.RemoveField(
            model_name='userexample',
            name='user',
        ),
        migrations.RemoveField(
            model_name='example',
            name='users',
        ),
        migrations.RemoveField(
            model_name='example',
            name='title',
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, help_text='Description of example'),
        ),
        migrations.AddField(
            model_name='example',
            name='title_not_verbose',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[geant_examples.validators.title_not_verbose_view]),
        ),
        migrations.AddField(
            model_name='example',
            name='title_verbose',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='tags',
            field=models.ManyToManyField(blank=True, default='Here can be description of example', related_name='examples', to='geant_examples.tag'),
        ),
        migrations.AddField(
            model_name='examplecommand',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_commands', to='geant_examples.example'),
        ),
        migrations.AddField(
            model_name='userexamplecommand',
            name='example_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geant_examples.examplecommand'),
        ),
        migrations.AddField(
            model_name='userexamplecommand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examplecommand',
            name='users',
            field=models.ManyToManyField(related_name='example_commands', through='geant_examples.UserExampleCommand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExampleGeant',
        ),
        migrations.DeleteModel(
            name='UserExample',
        ),
    ]
