# Generated by Django 5.1.5 on 2025-04-04 11:30

import geant_examples.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0007_examplecommand_userexamplecommand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='title_not_verbose',
            field=models.CharField(max_length=10, unique=True, validators=[geant_examples.validators.title_not_verbose_view]),
        ),
        migrations.AlterField(
            model_name='example',
            name='title_verbose',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
