# Generated by Django 5.1.5 on 2025-04-12 18:15

import django.db.models.deletion
import geant_examples.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0008_alter_example_title_not_verbose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('default', models.CharField(max_length=255)),
                ('order_index', models.IntegerField(validators=[geant_examples.validators.validate_index_order])),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='geant_examples.example')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'ordering': ('order_index',),
            },
        ),
        migrations.CreateModel(
            name='CommandValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='geant_examples.command')),
            ],
            options={
                'verbose_name': 'Value for command',
                'verbose_name_plural': 'Values for command',
            },
        ),
    ]
