# Generated by Django 5.1.5 on 2025-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0008_alter_example_title_not_verbose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(choices=[('Electromagnetism', 'Electromagnetism'), ('Hadron physics', 'Hadron physics'), ('Medicine', 'Medicine'), ('Optics', 'Optics'), ('Fields', 'Fields'), ('Other', 'Other')], default='Other', help_text='Category of example', max_length=255),
        ),
    ]
