# Generated by Django 5.1.5 on 2025-04-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0009_command_commandvalue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(fields=('example', 'order_index'), name='unique_constraint_index'),
        ),
    ]
