# Generated by Django 5.1.5 on 2025-04-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0010_command_unique_constraint_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandvalue',
            name='max',
        ),
        migrations.RemoveField(
            model_name='commandvalue',
            name='min',
        ),
        migrations.AddField(
            model_name='command',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
