# Generated by Django 5.1.5 on 2025-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0009_alter_example_category'),
        ('geant_examples', '0011_remove_commandvalue_max_remove_commandvalue_min_and_more'),
    ]

    operations = [
    ]
