# Generated by Django 5.1.5 on 2025-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0012_merge_20250415_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='synchronized',
            field=models.BooleanField(default=False),
        ),
    ]
