# Generated by Django 5.1.5 on 2025-06-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0013_example_synchronized'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Command List',
                'verbose_name_plural': 'Commands List',
            },
        ),
        migrations.AlterModelOptions(
            name='commandvalue',
            options={'verbose_name': 'Value for command list', 'verbose_name_plural': 'Values for command list'},
        ),
        migrations.RemoveField(
            model_name='commandvalue',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='command_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='geant_examples.commandlist'),
        ),
        migrations.AddField(
            model_name='commandvalue',
            name='command_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='command_values', to='geant_examples.commandlist'),
            preserve_default=False,
        ),
    ]
