# Generated by Django 5.1.5 on 2025-06-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0015_category_alter_example_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='category',
        ),
    ]
