# Generated by Django 5.1.5 on 2025-06-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0016_remove_example_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examples', to='geant_examples.category'),
        ),
    ]
