# Generated by Django 5.1.5 on 2025-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geant_examples', '0017_example_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
