name: Core CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WEB_BACKEND_HOST }}
          username: ${{ secrets.GEANT_USER }}
          key: ${{ secrets.WEB_BACKEND_SSH_PRIVATE_KEY }}
          script: |
            cd /home/alijan/Geant4_web_backend
            docker-compose -f docker-compose.prod.yml down
            git reset --hard HEAD
            git pull origin main          
            docker-compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml exec web-app python manage.py search_index --rebuild -f
