name: Core CD

on:
  workflow_run:
    workflows: ["Core CI"]  
    types:
      - completed
  pull_request:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.pull_request.merged == true}}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WEB_BACKEND_HOST }}
          username: ${{ secrets.GEANT_USER }}
          key: ${{ secrets.WEB_BACKEND_SSH_PRIVATE_KEY }}
          script: |
            cd /home/alijan/Geant4_web_backend
            docker-compose -f docker-compose.prod.yml down
            git config --global --add safe.directory /home/alijan/Geant4_web_backend
            git reset --hard HEAD
            git pull origin main          
            docker-compose -f docker-compose.prod.yml up -d

