name: Core CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WEB_BACKEND_HOST }}
          username: ${{ secrets.GEANT_USER }}
          key: ${{ secrets.WEB_BACKEND_SSH_PRIVATE_KEY }}
          script: |
            cd /home/alijan/Geant4_web_backend
            docker-compose -f docker-compose.prod.yml down
            git config --global --add safe.directory /home/alijan/Geant4_web_backend
            git reset --hard HEAD
            git pull origin main          
            docker-compose -f docker-compose.prod.yml up -d

